### ISSUE TITLE
converting wbxml to xml giving error

### ISSUE THREAD

**Issue by viswamraju** [davidpshaw/PyWBXMLDecoder#1]
converting wbxml (sync response for inbox folder) to xml giving error.

getting 196 as currentbyte.

**Comment by davidpshaw** [comment]
Attach the raw WBXML and I will take a look.  It could be a code page for 2013 or Office365 that was not part of this implementation, or it could be UTF-16 encoded.  Does the crashing string have a BOM at the start?
