### ISSUE TITLE
Execute the code

### ISSUE THREAD

**Issue by sauripanda** [davidpshaw/PyWBXMLDecoder#2]
Hi David,

Thanks for uploading this code, can you help with snippet of running the code with some sample.

Thanks
Sauri

**Comment by user185953** [comment]
PyWBXMLDecoder is used my [mitmproxy](https://github.com/mitmproxy/mitmproxy/tree/master/mitmproxy/contrib).  It may be a workable example.

**Comment by user185953** [comment]
Here. Binary wbxml goes in, text xml goes out
```
#!/usr/bin/python3.6
from mitmproxy.contrib.wbxml import ASCommandResponse
import sys

f = open(sys.argv[1], "rb") if len(sys.argv) > 1 else sys.stdin.buffer
parser = ASCommandResponse.ASCommandResponse(f.read())
print(parser.xmlString)
```
